// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: whitemagic-go/proto/mesh.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeshService_BroadcastSignal_FullMethodName   = "/whitemagic.MeshService/BroadcastSignal"
	MeshService_BroadcastHologram_FullMethodName = "/whitemagic.MeshService/BroadcastHologram"
	MeshService_DiscoverPeers_FullMethodName     = "/whitemagic.MeshService/DiscoverPeers"
)

// MeshServiceClient is the client API for MeshService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeshServiceClient interface {
	BroadcastSignal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	BroadcastHologram(ctx context.Context, in *HolographicSignal, opts ...grpc.CallOption) (*SignalResponse, error)
	DiscoverPeers(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error)
}

type meshServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshServiceClient(cc grpc.ClientConnInterface) MeshServiceClient {
	return &meshServiceClient{cc}
}

func (c *meshServiceClient) BroadcastSignal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, MeshService_BroadcastSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) BroadcastHologram(ctx context.Context, in *HolographicSignal, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, MeshService_BroadcastHologram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) DiscoverPeers(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoveryResponse)
	err := c.cc.Invoke(ctx, MeshService_DiscoverPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshServiceServer is the server API for MeshService service.
// All implementations must embed UnimplementedMeshServiceServer
// for forward compatibility.
type MeshServiceServer interface {
	BroadcastSignal(context.Context, *SignalRequest) (*SignalResponse, error)
	BroadcastHologram(context.Context, *HolographicSignal) (*SignalResponse, error)
	DiscoverPeers(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error)
	mustEmbedUnimplementedMeshServiceServer()
}

// UnimplementedMeshServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshServiceServer struct{}

func (UnimplementedMeshServiceServer) BroadcastSignal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastSignal not implemented")
}
func (UnimplementedMeshServiceServer) BroadcastHologram(context.Context, *HolographicSignal) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastHologram not implemented")
}
func (UnimplementedMeshServiceServer) DiscoverPeers(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverPeers not implemented")
}
func (UnimplementedMeshServiceServer) mustEmbedUnimplementedMeshServiceServer() {}
func (UnimplementedMeshServiceServer) testEmbeddedByValue()                     {}

// UnsafeMeshServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshServiceServer will
// result in compilation errors.
type UnsafeMeshServiceServer interface {
	mustEmbedUnimplementedMeshServiceServer()
}

func RegisterMeshServiceServer(s grpc.ServiceRegistrar, srv MeshServiceServer) {
	// If the following call panics, it indicates UnimplementedMeshServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeshService_ServiceDesc, srv)
}

func _MeshService_BroadcastSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).BroadcastSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_BroadcastSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).BroadcastSignal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_BroadcastHologram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HolographicSignal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).BroadcastHologram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_BroadcastHologram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).BroadcastHologram(ctx, req.(*HolographicSignal))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_DiscoverPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).DiscoverPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_DiscoverPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).DiscoverPeers(ctx, req.(*DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeshService_ServiceDesc is the grpc.ServiceDesc for MeshService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeshService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whitemagic.MeshService",
	HandlerType: (*MeshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastSignal",
			Handler:    _MeshService_BroadcastSignal_Handler,
		},
		{
			MethodName: "BroadcastHologram",
			Handler:    _MeshService_BroadcastHologram_Handler,
		},
		{
			MethodName: "DiscoverPeers",
			Handler:    _MeshService_DiscoverPeers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whitemagic-go/proto/mesh.proto",
}
