// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: whitemagic-go/proto/mesh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SignalType    string                 `protobuf:"bytes,2,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_whitemagic_go_proto_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *SignalRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SignalRequest) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *SignalRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SignalRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HolographicSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Coordinates   []float32              `protobuf:"fixed32,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"` // 4D: [x (logic), y (micro), z (time), w (importance)]
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Importance    float32                `protobuf:"fixed32,4,opt,name=importance,proto3" json:"importance,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceNode    string                 `protobuf:"bytes,6,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolographicSignal) Reset() {
	*x = HolographicSignal{}
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolographicSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolographicSignal) ProtoMessage() {}

func (x *HolographicSignal) ProtoReflect() protoreflect.Message {
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolographicSignal.ProtoReflect.Descriptor instead.
func (*HolographicSignal) Descriptor() ([]byte, []int) {
	return file_whitemagic_go_proto_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *HolographicSignal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HolographicSignal) GetCoordinates() []float32 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *HolographicSignal) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *HolographicSignal) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *HolographicSignal) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HolographicSignal) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_whitemagic_go_proto_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *SignalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_whitemagic_go_proto_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoveryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DiscoveryRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*NodeInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_whitemagic_go_proto_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoveryResponse) GetPeers() []*NodeInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_whitemagic_go_proto_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_whitemagic_go_proto_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_whitemagic_go_proto_mesh_proto protoreflect.FileDescriptor

const file_whitemagic_go_proto_mesh_proto_rawDesc = "" +
	"\n" +
	"\x1ewhitemagic-go/proto/mesh.proto\x12\n" +
	"whitemagic\"\x85\x01\n" +
	"\rSignalRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsignal_type\x18\x02 \x01(\tR\n" +
	"signalType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xc7\x01\n" +
	"\x11HolographicSignal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vcoordinates\x18\x02 \x03(\x02R\vcoordinates\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\x12\x1e\n" +
	"\n" +
	"importance\x18\x04 \x01(\x02R\n" +
	"importance\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vsource_node\x18\x06 \x01(\tR\n" +
	"sourceNode\"D\n" +
	"\x0eSignalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x10DiscoveryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"?\n" +
	"\x11DiscoveryResponse\x12*\n" +
	"\x05peers\x18\x01 \x03(\v2\x14.whitemagic.NodeInfoR\x05peers\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress2\xf5\x01\n" +
	"\vMeshService\x12H\n" +
	"\x0fBroadcastSignal\x12\x19.whitemagic.SignalRequest\x1a\x1a.whitemagic.SignalResponse\x12N\n" +
	"\x11BroadcastHologram\x12\x1d.whitemagic.HolographicSignal\x1a\x1a.whitemagic.SignalResponse\x12L\n" +
	"\rDiscoverPeers\x12\x1c.whitemagic.DiscoveryRequest\x1a\x1d.whitemagic.DiscoveryResponseB\x15Z\x13whitemagic-go/protob\x06proto3"

var (
	file_whitemagic_go_proto_mesh_proto_rawDescOnce sync.Once
	file_whitemagic_go_proto_mesh_proto_rawDescData []byte
)

func file_whitemagic_go_proto_mesh_proto_rawDescGZIP() []byte {
	file_whitemagic_go_proto_mesh_proto_rawDescOnce.Do(func() {
		file_whitemagic_go_proto_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_whitemagic_go_proto_mesh_proto_rawDesc), len(file_whitemagic_go_proto_mesh_proto_rawDesc)))
	})
	return file_whitemagic_go_proto_mesh_proto_rawDescData
}

var file_whitemagic_go_proto_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_whitemagic_go_proto_mesh_proto_goTypes = []any{
	(*SignalRequest)(nil),     // 0: whitemagic.SignalRequest
	(*HolographicSignal)(nil), // 1: whitemagic.HolographicSignal
	(*SignalResponse)(nil),    // 2: whitemagic.SignalResponse
	(*DiscoveryRequest)(nil),  // 3: whitemagic.DiscoveryRequest
	(*DiscoveryResponse)(nil), // 4: whitemagic.DiscoveryResponse
	(*NodeInfo)(nil),          // 5: whitemagic.NodeInfo
}
var file_whitemagic_go_proto_mesh_proto_depIdxs = []int32{
	5, // 0: whitemagic.DiscoveryResponse.peers:type_name -> whitemagic.NodeInfo
	0, // 1: whitemagic.MeshService.BroadcastSignal:input_type -> whitemagic.SignalRequest
	1, // 2: whitemagic.MeshService.BroadcastHologram:input_type -> whitemagic.HolographicSignal
	3, // 3: whitemagic.MeshService.DiscoverPeers:input_type -> whitemagic.DiscoveryRequest
	2, // 4: whitemagic.MeshService.BroadcastSignal:output_type -> whitemagic.SignalResponse
	2, // 5: whitemagic.MeshService.BroadcastHologram:output_type -> whitemagic.SignalResponse
	4, // 6: whitemagic.MeshService.DiscoverPeers:output_type -> whitemagic.DiscoveryResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_whitemagic_go_proto_mesh_proto_init() }
func file_whitemagic_go_proto_mesh_proto_init() {
	if File_whitemagic_go_proto_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_whitemagic_go_proto_mesh_proto_rawDesc), len(file_whitemagic_go_proto_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_whitemagic_go_proto_mesh_proto_goTypes,
		DependencyIndexes: file_whitemagic_go_proto_mesh_proto_depIdxs,
		MessageInfos:      file_whitemagic_go_proto_mesh_proto_msgTypes,
	}.Build()
	File_whitemagic_go_proto_mesh_proto = out.File
	file_whitemagic_go_proto_mesh_proto_goTypes = nil
	file_whitemagic_go_proto_mesh_proto_depIdxs = nil
}
