#!/usr/bin/env python3
"""
Minimal Whitemagic Agent Example
Shows how to use tools directly from code.

Quick setup:
    pip install whitemagic
    wm init          # scaffolds README, run.sh, playground.py, .env
    python playground.py   # interactive demo (generated by wm init)
"""
import os
from whitemagic.tools.unified_api import call_tool

def main():
    # 1. Environment Configuration
    # Whitemagic is "offline-first". It respects WM_STATE_ROOT for all data.
    os.environ["WM_STATE_ROOT"] = "/tmp/whitemagic_agent_example"
    os.environ["WM_SILENT_INIT"] = "1"

    print("🌌 Whitemagic Agent Minimal Example")
    print("-" * 40)

    # 2. Check Capabilities
    print("Checking capabilities...")
    resp = call_tool("capabilities", include_tools=True)
    if resp["status"] == "success":
        print(f"✅ Whitemagic v{resp['details']['version']} active.")
        # print(f"Available tools: {list(resp['details']['tools'].keys())[:10]}...")

    # 3. Memory Round-trip
    print("\nStoring a memory...")
    call_tool("remember", text="The secret password is 'whitemagic-123'", tags=["logic", "test"])
    
    print("Recalling memory...")
    search = call_tool("recall", query="secret password")
    if search["status"] == "success" and search["results"]:
        top_match = search["results"][0]["content"]
        print(f"✅ Found: {top_match}")

    # 4. Manifest / State Summary
    print("\nSystem State Summary:")
    state = call_tool("state.summary")
    if state["status"] == "success":
        print(f"   Root: {state['details']['root']}")
        print(f"   Memory Count: {state['details'].get('memory_count', 'unknown')}")

    print("\nDone. All data stored in /tmp/whitemagic_agent_example")

if __name__ == "__main__":
    main()
