#!/bin/bash
# System Optimizations for LLM Inference
# Generated by optimize_system_for_llm.py

echo "Applying system optimizations for LLM inference..."

# 1. Set CPU governor to performance (requires sudo)
echo "Setting CPU governor to performance mode..."
sudo cpupower frequency-set -g performance 2>/dev/null || echo "  (Skipped - cpupower not available or no sudo)"

# 2. Increase Ollama process priority (requires sudo)
OLLAMA_PID=$(ps aux | grep 'ollama serve' | grep -v grep | awk '{print $2}')
if [ -n "$OLLAMA_PID" ]; then
    echo "Increasing Ollama priority (PID: $OLLAMA_PID)..."
    sudo renice -n -5 -p $OLLAMA_PID 2>/dev/null || echo "  (Skipped - no sudo)"
else
    echo "Ollama not running - start with: ollama serve"
fi

# 3. Set Ollama environment variables for better performance
export OLLAMA_NUM_PARALLEL=1  # Single request at a time for max speed
export OLLAMA_MAX_LOADED_MODELS=1  # Keep only one model in memory
export OLLAMA_FLASH_ATTENTION=true  # Enable flash attention if supported

echo ""
echo "Optimizations applied!"
echo "Note: CPU governor changes require sudo and may not persist after reboot"
echo ""
echo "To make CPU governor permanent, add to /etc/rc.local:"
echo "  cpupower frequency-set -g performance"
