#!/usr/bin/env python3
"""
Generate docs/MCP_TOOLS_QUICK_REFERENCE.md from the canonical tool registry.

Why this exists:
- The tool surface area changes frequently.
- Hand-maintained tool lists drift and confuse both humans and agents.

This script loads `whitemagic/tools/registry.py` directly from its file path to
avoid importing the `whitemagic.tools` package (which has runtime side effects).
"""

from __future__ import annotations

import datetime as _dt
import importlib.util
from pathlib import Path
from typing import Any


def _load_registry_module(path: Path) -> Any:
    spec = importlib.util.spec_from_file_location("_wm_tool_registry", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load module spec from {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    registry_path = repo_root / "whitemagic" / "tools" / "registry.py"
    out_path = repo_root / "docs" / "MCP_TOOLS_QUICK_REFERENCE.md"

    reg = _load_registry_module(registry_path)
    tools = list(reg.TOOL_REGISTRY)

    # Sort by stable name for deterministic docs.
    tools.sort(key=lambda t: t.name)

    generated = _dt.date.today().isoformat()

    lines: list[str] = []
    lines.append("# WhiteMagic MCP Tools - Quick Reference")
    lines.append("")
    lines.append(
        f"Auto-generated by `python scripts/generate_mcp_tools_quick_reference.py` on {generated}."
    )
    lines.append("")
    lines.append(f"- Total tools: {len(tools)}")
    lines.append("")
    lines.append("## Tools (Alphabetical)")
    lines.append("")
    lines.append("| Name | Category | Safety | Description |")
    lines.append("| --- | --- | --- | --- |")
    for t in tools:
        desc = (t.description or "").replace("\n", " ").strip()
        # Keep table readable; full schemas live in code.
        if len(desc) > 160:
            desc = desc[:157] + "..."
        lines.append(f"| `{t.name}` | `{t.category.value}` | `{t.safety.value}` | {desc} |")
    lines.append("")

    out_path.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out_path} ({len(tools)} tools)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
